### ISSUE TITLE
pyranges has both the option to extract fasta regions and a much faster Fisher Exact

### ISSUE THREAD

**Issue by endrebak** [stephenkraemer/regionset_profiler#1]
Just FYI, I do not mind you using other libs, of course, XD.

https://pyranges.readthedocs.io/en/latest/autoapi/pyranges/get_fasta/index.html

If you have many tests to perform, the pyranges-version of fisher exact is much faster. I had a collection of tests that took eight hours to run with Scipy, but the PyRanges-version took about 90 seconds IIRC. 

You do not even need pyranges; a simple implementation is found here: https://stackoverflow.com/questions/34947578/how-to-vectorize-fishers-exact-test/58661068#58661068

**Comment by stephenkraemer** [comment]
Hi,
thanks for the feedback, I do appreciate it, and of course you are right. This repo is a somewhat historic eclectic code base, and development started before I discovered pyranges. It's currently mainly here as source code for a paper we submitted. If I extend the functionality in the future, I'll keep your pointers in mind, and will never mind anything else you find :)

Heads up: I might need to publish some other pre-pyranges code in the next weeks - won't happen again in the next projects :)

**Comment by stephenkraemer** [comment]
another note in case this repo is ever interesting for someone other than me: for the 2x2 case, the test should definitely be switched. For the mxc case, this uses https://github.com/maclandrol/FisherExact, which is pretty fast, I think. Also, if score-based enrichments (instead of binary on/off) are used, it will use KS or Mann-Whitney, which is also slow.

**Comment by endrebak** [comment]
I think bedtools and pybedtools are great too, but I have a strong preference for using only Python where possible :)

If you need help with pyranges or have feature-requests, please feel free to contact me.
